default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dobermen_development

test:
  <<: *default
  database: dobermen_test

production:
  <<: *default
  database: dobermen_production
  username: dobermen
  password: <%= ENV['dobermen_DATABASE_PASSWORD'] %>
